name: Paste & Commit

on:
  workflow_dispatch:
    inputs:
      path:
        description: '파일 경로 (예: brotem_final.py)'
        required: true
        default: 'brotem_final.py'
      message:
        description: '커밋 메시지'
        required: true
        default: 'chore: update from Action input'
      content_b64:
        description: '파일 내용(Base64 인코딩한 문자열)'
        required: true

jobs:
  write-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decode and write file
        run: |
          python - << 'PY'
          import os,base64
          p = os.environ['PATH_INPUT']
          b64 = os.environ['CONTENT_B64']
          data = base64.b64decode(b64.encode('utf-8'))
          if '/' in p:
            os.makedirs(os.path.dirname(p), exist_ok=True)
          with open(p, 'wb') as f:
            f.write(data)
          PY
        env:
          PATH_INPUT: ${{ github.event.inputs.path }}
          CONTENT_B64: ${{ github.event.inputs.content_b64 }}

      - name: Commit & Push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${{ github.event.inputs.path }}"
          git commit -m "${{ github.event.inputs.message }}" || echo "No changes"
          git push
